[RFC][UN-8328] Migrate uni-form
uniplaces/ember-cli-uniq pull request #104
Opened 2017-02-28 11:24 UTC by AndreJoaquim

https://uniplaces.atlassian.net/browse/UN-8328

2017-02-28 11:26 UTC, mmelo approved these changes
@AndreJoaquim 💯

2017-02-28 11:49 UTC, montoias requested changes

2017-02-28 11:49 UTC, montoias commented on app/components/uni-form.js
> +export { default } from 'ember-cli-uniq/components/uni-form';
new line

2017-03-01 09:52 UTC, AndreJoaquim commented on app/components/uni-form.js
> +export { default } from 'ember-cli-uniq/components/uni-form';
Done :)

2017-03-01 11:21 UTC, montoias approved these changes

2017-03-02 15:12 UTC, merged