[RFC][UN-6614] Improvements to uniq
uniplaces/ember-cli-uniq pull request #12
Opened 2016-10-27 14:17 UTC by mmelo

Refers to: https://uniplaces.atlassian.net/browse/UN-6614

Added uni-alert component and made some minor style and behaviour fixes

2016-10-27 15:51 UTC, raffo0707 reviewed
remove typings/ember/ember.d.ts

2016-10-27 15:51 UTC, raffo0707 commented on .vscodeignore
> +libpeerconnection.log
new line

2016-10-27 15:51 UTC, raffo0707 commented on app/components/uni-subtitle.js
> +export { default } from 'ember-cli-uniq/components/uni-subtitle';
new line

2016-10-27 15:51 UTC, raffo0707 commented on app/components/uni-alert.js
> +export { default } from 'ember-cli-uniq/components/uni-alert';
new line

2016-10-27 15:51 UTC, raffo0707 commented on jsconfig.json
> +{"compilerOptions":{"target":"es6","experimentalDecorators":true},"exclude":["node_modules","bower_components","tmp","vendor",".git","dist"]}
new line

2016-10-27 15:51 UTC, raffo0707 commented on public/assets/images/icons/icon-warning.svg
> +<path fillrule="evenodd" d="M 11 22C 4.93 22-0 17.07-0 11-0 4.93 4.93 0 11 0 17.07 0 22 4.93 22 11 22 17.07 17.07 22 11 22ZM 11 1.76C 5.91 1.76 1.76 5.91 1.76 11 1.76 16.09 5.91 20.24 11 20.24 16.09
new line, check your configurations, editors usually have an option to put an empty line at the end if it's missing

2016-10-27 15:57 UTC, AndreJoaquim requested changes

2016-10-27 15:57 UTC, AndreJoaquim commented on addon/templates/components/uni-step-card.hbs
> +<div class="uni-step-card__hint">{{{title}}}</div>
should be hint

2016-10-27 15:57 UTC, AndreJoaquim commented on addon/templates/components/uni-subtitle.hbs
> +{{subtitle}}
we might need to inject some HTML here... :D

change to ```{{{subtitle}}}```

2016-10-27 15:57 UTC, AndreJoaquim commented on addon/templates/components/uni-title.hbs
> +    <p class="uni-title__subtitle">{{{subtitle}}}</p>
Use  {{uni-subtitle subtitle=subtitle}}

2016-10-27 15:57 UTC, AndreJoaquim commented on app/components/uni-alert.js
> +export { default } from 'ember-cli-uniq/components/uni-alert';
newline

2016-10-27 15:57 UTC, AndreJoaquim commented on app/components/uni-subtitle.js
> +export { default } from 'ember-cli-uniq/components/uni-subtitle';
newline

2016-10-27 15:57 UTC, AndreJoaquim commented on jsconfig.json
> +{"compilerOptions":{"target":"es6","experimentalDecorators":true},"exclude":["node_modules","bower_components","tmp","vendor",".git","dist"]}
why do we need this?

2016-10-27 15:57 UTC, AndreJoaquim commented on public/assets/images/icons/icon-warning.svg
> +<path fillrule="evenodd" d="M 11 22C 4.93 22-0 17.07-0 11-0 4.93 4.93 0 11 0 17.07 0 22 4.93 22 11 22 17.07 17.07 22 11 22ZM 11 1.76C 5.91 1.76 1.76 5.91 1.76 11 1.76 16.09 5.91 20.24 11 20.24 16.09
newline

2016-10-27 15:58 UTC, AndreJoaquim commented
As raffa said, I don't know what is that ember.d.ts but probably we don't need it :)

2016-10-27 16:00 UTC, montoias requested changes

2016-10-27 16:00 UTC, montoias commented on .vscodeignore
> +libpeerconnection.log
why do we need  .vscodeignore ? remove this file.

2016-10-27 16:00 UTC, montoias commented on jsconfig.json
> +{"compilerOptions":{"target":"es6","experimentalDecorators":true},"exclude":["node_modules","bower_components","tmp","vendor",".git","dist"]}
remove this, this is VS generated files

2016-10-27 16:04 UTC, montoias commented
@AndreJoaquim it's the VScode editor. Remove all of that files that I mentioned

2016-10-31 16:19 UTC, mmelo commented on public/assets/images/icons/icon-warning.svg
> +<path fillrule="evenodd" d="M 11 22C 4.93 22-0 17.07-0 11-0 4.93 4.93 0 11 0 17.07 0 22 4.93 22 11 22 17.07 17.07 22 11 22ZM 11 1.76C 5.91 1.76 1.76 5.91 1.76 11 1.76 16.09 5.91 20.24 11 20.24 16.09
svg's will be dealt with on build so it does not impact anything right now.

2016-10-31 16:21 UTC, mmelo commented on app/components/uni-alert.js
> +export { default } from 'ember-cli-uniq/components/uni-alert';
done

2016-10-31 16:22 UTC, mmelo commented on public/assets/images/icons/icon-warning.svg
> +<path fillrule="evenodd" d="M 11 22C 4.93 22-0 17.07-0 11-0 4.93 4.93 0 11 0 17.07 0 22 4.93 22 11 22 17.07 17.07 22 11 22ZM 11 1.76C 5.91 1.76 1.76 5.91 1.76 11 1.76 16.09 5.91 20.24 11 20.24 16.09
svg's will be dealt with on build, so this has no impact right now.

2016-10-31 16:23 UTC, mmelo commented on app/components/uni-alert.js
> +export { default } from 'ember-cli-uniq/components/uni-alert';
done

2016-10-31 16:23 UTC, mmelo commented on app/components/uni-subtitle.js
> +export { default } from 'ember-cli-uniq/components/uni-subtitle';
done

2016-10-31 16:24 UTC, montoias commented
reviewed

2016-10-31 19:17 UTC, AndreJoaquim commented
Remove .DS_Store file

2016-11-02 10:50 UTC, merged