[RFC][UN-8400] Variable pricing on enricher frontend
uniplaces/ember-cli-uniq pull request #124
Opened 2017-03-16 18:57 UTC by henrmota

https://uniplaces.atlassian.net/browse/UN-8400

2017-03-17 14:48 UTC, AndreJoaquim requested changes

2017-03-17 14:48 UTC, AndreJoaquim commented on addon/components/uni-input-price.js
> +      return this.get('value') === null ? '' : `${this.get('value')}`;
```js
return isPresent(this.get('value')) ? `${this.get('value')}` : '';
```
or
```js
return isEmpty(this.get('value')) ? '': `${this.get('value')}`;
```

2017-03-17 14:48 UTC, AndreJoaquim commented on addon/components/uni-input-price.js
> +  numberAsString: computed('value', {
numberAsInt

2017-03-17 14:48 UTC, AndreJoaquim commented on addon/components/uni-input-price.js
> +        let newValue = this._isInt(value) ? parseInt(value) : value;
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/isInteger

2017-03-17 14:48 UTC, AndreJoaquim commented on addon/components/uni-input-price.js
> +        return newValue;
Remove this return

2017-03-17 14:48 UTC, AndreJoaquim commented on addon/components/uni-input-price.js
> +      return value;
Do you need to return on the set?

2017-03-17 14:48 UTC, AndreJoaquim commented on addon/components/uni-input-price.js
> +  _isInt(value) {
Remove this function

2017-03-17 14:48 UTC, AndreJoaquim commented on addon/templates/components/uni-input-price.hbs
> +  value=numberAsString
numberAsInt

2017-03-17 14:48 UTC, AndreJoaquim commented on addon/templates/components/uni-input-price.hbs
> +
Remove empty line

2017-03-17 14:48 UTC, AndreJoaquim commented on addon/templates/components/uni-input-price.hbs
> +  <span>{{currency}}</span>
Remove empty spaces at EOL

2017-03-22 09:44 UTC, AndreJoaquim approved these changes
Good work! 👍

2017-03-22 16:03 UTC, montoias requested changes

2017-03-22 16:03 UTC, montoias commented on addon/components/uni-input-price.js
> +        return value;
new line

2017-03-22 16:03 UTC, montoias commented on addon/components/uni-input-price.js
> +      return newValue;
new line

2017-03-22 16:03 UTC, montoias commented on addon/components/uni-input-price.js
> +      return isEmpty(this.get('value')) ? '' : `${this.get('value')}`;
Make sure the 'value' variable has a default value of empty string.

```js
get() {
   return this.get('value');
}
```

2017-03-22 16:38 UTC, montoias approved these changes

2017-03-22 18:43 UTC, merged