[RFC][UN-8937] Redesign checkbox component
uniplaces/ember-cli-uniq pull request #134
Opened 2017-04-19 17:38 UTC by niceoutput

2017-04-19 17:42 UTC, telmaantunes approved these changes

2017-04-19 17:42 UTC, telmaantunes commented on bower.json
> +    "uniq": "#change-checkbox-component"
before merging don't forget tho change uniq version

2017-04-19 17:52 UTC, AndreJoaquim requested changes

2017-04-19 17:52 UTC, AndreJoaquim commented on addon/templates/components/uni-checkbox.hbs
> +    <input
Fix indentation to 2 spaces

2017-04-19 17:52 UTC, AndreJoaquim commented on addon/templates/components/uni-checkbox.hbs
> +      class="uni-checkbox">
```hbs
class=(i "uni-checkbox ${disabledClass}" disabledClass={{if isDisabled uni-checkbox--disabled ''}})
```

2017-04-19 17:52 UTC, AndreJoaquim commented on addon/templates/components/uni-checkbox.hbs
> +      class="uni-checkbox">
I would rather add the styles to the modifier ```--disabled``` instead of the ```disabled```

2017-04-19 17:52 UTC, AndreJoaquim commented on addon/templates/components/uni-checkbox.hbs
> +      class="uni-checkbox">
You will also need this if checks for error, warning, etc.

e.g. ```{{if isError "uni-checkbox--error" ''}}```

2017-04-19 17:52 UTC, AndreJoaquim commented on addon/templates/components/uni-checkbox.hbs
> +    <label for={{i '${id}-checkbox' id=elementId}}>{{label}}</label>
Use {{{ instead of  {{ . This allows to evaluate HTML if the label has some.

E.g. label = ```<strong>xpto</strong>```

2017-04-19 17:52 UTC, AndreJoaquim commented on bower.json
> +    "uniq": "#change-checkbox-component"
Revert this change

2017-04-19 17:52 UTC, AndreJoaquim commented on public/assets/images/icons/checkbox-icon.svg
> +<svg xmlns="http://www.w3.org/2000/svg" width="14" height="11.3" viewBox="0 0 14 11.3"><polygon fill="#fff" class="cls-1" points="12.2 0 4.8 7.8 1.7 4.7 0 6.5 4.8 11.3 14 1.7 12.2 0"/></svg>
Polygons shouldn't not have fill nor class attributes :) We had problems with this before

2017-04-19 17:52 UTC, AndreJoaquim commented on addon/styles/partials/_uni-checkbox.scss
> +                background-image: url("images/icons/checkbox-icon.svg");
Why isn't this an inline svg? After talking to Melo, he said this will not work because of the svg path.

2017-04-20 10:13 UTC, AndreJoaquim approved these changes

2017-04-20 14:23 UTC, AndreJoaquim approved these changes

2017-04-20 14:23 UTC, AndreJoaquim commented on addon/templates/components/uni-checkbox.hbs
> +    {{#if isSelected }}
Remove extra space

2017-04-20 14:32 UTC, asantos00 commented on addon/styles/partials/_uni-checkbox.scss
> +  }
Fix identation

2017-04-20 14:43 UTC, asantos00 approved these changes

2017-04-24 13:35 UTC, asantos00 commented
Commit fdb5677 fixes checkbox on mobile and supports checkbox with text in two lines.

![screen shot 2017-04-24 at 14 34 36](https://cloud.githubusercontent.com/assets/2593480/25339634/4093808a-28fb-11e7-9f3f-ec78e4cd3125.png)

2017-04-24 14:40 UTC, niceoutput reviewed
That's ok

2017-04-26 10:09 UTC, mmelo approved these changes
reviewd! 💯  (as requested by @DaniFrancisco)

2017-04-26 10:25 UTC, AndreJoaquim approved these changes

2017-04-26 14:25 UTC, merged