[RFC][UN-8896] add tooltips on inputs, minor bug fix
uniplaces/ember-cli-uniq pull request #144
Opened 2017-04-27 14:40 UTC by telmaantunes

https://uniplaces.atlassian.net/browse/UN-8896

* textarea
![screen shot 2017-04-27 at 15 35 20](https://cloud.githubusercontent.com/assets/8360946/25488699/9eaa0bce-2b5f-11e7-981e-3d0dcee6bb2d.png)
![screen shot 2017-04-27 at 15 35 25](https://cloud.githubusercontent.com/assets/8360946/25488704/9fb73726-2b5f-11e7-9371-d2c7b49a7f08.png)

* countries
![screen shot 2017-04-27 at 15 24 18](https://cloud.githubusercontent.com/assets/8360946/25488745/be1bd21c-2b5f-11e7-9275-029d91dee8e0.png)
![screen shot 2017-04-27 at 15 24 24](https://cloud.githubusercontent.com/assets/8360946/25488746/be2a1124-2b5f-11e7-8332-45f25d914713.png)

* fixed a border radius bug here
![screen shot 2017-04-27 at 15 40 12](https://cloud.githubusercontent.com/assets/8360946/25488780/d89abca2-2b5f-11e7-81ee-e21e305f963a.png)

2017-04-27 14:42 UTC, AndreJoaquim commented
TOOLTIPS EVERYWHERE!

2017-04-27 14:44 UTC, AndreJoaquim requested changes

2017-04-27 14:44 UTC, AndreJoaquim commented on addon/styles/partials/_uni-mobile-number.scss
> +  display: inline-flex;
```sass
@include inline-flex()
```

2017-04-27 14:44 UTC, AndreJoaquim commented on addon/styles/partials/_uni-textarea.scss
>    margin-bottom: 46px;
👀

2017-04-27 14:44 UTC, AndreJoaquim commented on tests/dummy/app/templates/application.hbs
> -  {{uni-mobile-number preferredCountries=(array 'PT' 'DE' 'GB')}}
Can you keep one without tooltip?

2017-04-27 14:49 UTC, telmaantunes commented on addon/styles/partials/_uni-textarea.scss
>    margin-bottom: 46px;
indeed 😿

2017-04-28 09:08 UTC, AndreJoaquim approved these changes

2017-05-03 10:39 UTC, merged