[RFC][UN-8746] Add error options
uniplaces/ember-cli-uniq pull request #171
Opened 2017-06-19 09:49 UTC by asantos00

https://uniplaces.atlassian.net/browse/UN-8746

2017-06-19 09:52 UTC, fredcerdeira requested changes

2017-06-19 09:52 UTC, fredcerdeira commented on addon/styles/partials/_uni-dropdown.scss
> +    border-color: color('feedback', 'error');
Double quotes here

2017-06-19 09:52 UTC, fredcerdeira commented on addon/styles/partials/_uni-textarea.scss
> +      border-color: color('feedback', 'error');
Double quotes here

2017-06-19 09:52 UTC, fredcerdeira commented on addon/styles/partials/_uni-textarea.scss
>      color: color('text', 'subheader');
Double quotes here

2017-06-19 10:23 UTC, asantos00 commented on addon/styles/partials/_uni-dropdown.scss
> +    border-color: color('feedback', 'error');
From what I've searched, we normally use single quotes.

https://github.com/uniplaces/ember-cli-uniq/search?p=2&q=color%28%22&type=&utf8=%E2%9C%93

2017-06-19 10:23 UTC, mmelo approved these changes
nothing to add to what @fredcerdeira identified. 👍

2017-06-19 10:25 UTC, fredcerdeira commented on addon/styles/partials/_uni-dropdown.scss
> +    border-color: color('feedback', 'error');
I the lastest discussions about this topic we agreed that for CSS we should keep double quotes but confirm with another reviewer

2017-06-19 17:07 UTC, AndreJoaquim commented
I believe that in this addon, we use single quotes everywhere. Why we did/do it? Can't remember. But it's better to keep a "bad" standard but consistent instead of creating unnecessary inconsistencies

2017-06-20 10:36 UTC, AndreJoaquim approved these changes

2017-06-20 10:39 UTC, fredcerdeira approved these changes

2017-06-20 10:41 UTC, merged