Add disabled support to uni-input-price
uniplaces/ember-cli-uniq pull request #186
Opened 2017-07-31 17:09 UTC by henrmota

https://uniplaces.atlassian.net/browse/UN-9605

2017-08-01 10:30 UTC, mmelo requested changes

2017-08-01 10:30 UTC, mmelo commented on addon/styles/partials/_uni-input-price.scss
> +    color: color('input', 'disabled');
use double quotes here please

2017-08-01 10:30 UTC, mmelo commented on addon/styles/partials/_uni-input-price.scss
> +    background-color: #f0f1f3;
double check if this exists in uniplaces-uniq color palette

2017-08-01 10:30 UTC, mmelo commented on addon/styles/partials/_uni-input-price.scss
> +      background-color: #f0f1f3;
same here

2017-08-01 10:49 UTC, mmelo approved these changes

2017-08-02 16:15 UTC, AndreJoaquim requested changes

2017-08-02 16:15 UTC, AndreJoaquim commented on addon/components/uni-input-price.js
> +  classNameBindings: ['isDisabled:uni-input-price--disabled'],
Add an example of this case to the demo.

2017-08-02 16:47 UTC, AndreJoaquim approved these changes

2017-08-07 16:20 UTC, merged