[RFC][NI] Minor fix in uni-select
uniplaces/ember-cli-uniq pull request #188
Opened 2017-08-29 15:55 UTC by AndreJoaquim

NI

2017-08-29 16:08 UTC, mmelo approved these changes

2017-08-30 09:49 UTC, telmaantunes requested changes
⚠️  can you please check if the credit cards select on the payment page still work with these changes before merging?
thanks

2017-09-07 09:45 UTC, AndreJoaquim commented
@telmaantunes sure, sure

2017-12-14 15:53 UTC, AndreJoaquim commented
![screen shot 2017-12-07 at 16 54 05](https://user-images.githubusercontent.com/5813769/34001062-e683adfa-e0e6-11e7-85f8-06857b57051c.png)

2017-12-14 15:55 UTC, mmelo approved these changes

2017-12-15 18:06 UTC, telmaantunes approved these changes

2017-12-15 18:10 UTC, merged