Add calendar icon to data input
uniplaces/ember-cli-uniq pull request #192
Opened 2017-09-21 17:14 UTC by henrmota

2017-09-21 17:19 UTC, AndreJoaquim requested changes

2017-09-21 17:19 UTC, AndreJoaquim commented on addon/styles/partials/_uni-datepicker-input.scss
> +  &__wrapper {
Fix formatting for this file

2017-09-21 17:19 UTC, AndreJoaquim commented on addon/templates/components/uni-datepicker-input.hbs
> +  {{inline-svg 'icons/calendar'}}
Fix indentation

2017-09-25 09:32 UTC, mmelo requested changes
minor changes requested

2017-09-25 09:32 UTC, mmelo commented on addon/styles/partials/_uni-datepicker-input.scss
> +          fill: #00adef !important;
`fill: color("primary");`

2017-09-25 09:32 UTC, mmelo commented on public/assets/images/icons/calendar.svg
> +<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 17 18.59"><g fill="#575757"><path d="M16.43 1.38h-2.19V.57a.57.57 0 0 0-.57-.57H11.6a.57.57 0 0 0-.6.57v.81H6V.57A.57.57 0 0 0 5.4 0H3.33a.57.57 0
newline EOF

2017-09-25 10:56 UTC, AndreJoaquim requested changes

2017-09-25 10:56 UTC, AndreJoaquim commented on addon/styles/partials/_uni-datepicker-input.scss
> +    &__icon{
Missing space

2017-09-25 10:56 UTC, AndreJoaquim commented on addon/styles/partials/_uni-datepicker-input.scss
> +        path{
Missing space

2017-09-25 10:57 UTC, AndreJoaquim commented
Please provide some screenshots

2017-09-25 11:00 UTC, AndreJoaquim approved these changes

2017-09-25 11:03 UTC, mmelo approved these changes

2017-09-25 13:52 UTC, merged