[WIP][NI] Update ember to 2.16 and migrate to the new module API
uniplaces/ember-cli-uniq pull request #203
Opened 2017-10-18 10:58 UTC by AndreJoaquim

NI

2017-10-27 16:13 UTC, asantos00 requested changes
Good job, and good job using `ember-try` 👏

2017-10-27 16:13 UTC, asantos00 commented on .gitignore
> +yarn-error.log
I think you can do `./*.log`, I don't see us wanting to commit log files

2017-10-27 16:13 UTC, asantos00 commented on addon/components/uni-modal.js
> +import $ from 'jquery';
oh 😞

2017-11-07 16:28 UTC, asantos00 approved these changes

2017-11-07 16:31 UTC, mmelo approved these changes

2017-11-07 17:37 UTC, telmaantunes commented on .gitignore
> -.DS_Store
why remove these two?

2017-11-09 16:20 UTC, AndreJoaquim commented on .gitignore
> -.DS_Store
Mea culpa

2017-11-09 16:38 UTC, DaniFrancisco approved these changes
:1st_place_medal:

2017-11-09 17:09 UTC, merged