[RFC][UN-11305] Add description to uni header dropdown items
uniplaces/ember-cli-uniq pull request #212
Opened 2017-12-26 14:24 UTC by sardyy

https://uniplaces.atlassian.net/browse/UN-11305

Why do I need this?

<img width="356" alt="screen shot 2017-12-26 at 11 43 57" src="https://user-images.githubusercontent.com/12813036/34358467-e67a8756-ea47-11e7-9598-02439346c0cf.png">

Basically, I've needed to implement the above component and I've realized that it's quite similar to ```uni-header-dropdown```with a description below the option. So instead of creating a new component, I've just adapted it.

2017-12-26 15:15 UTC, asantos00 commented
Huuum, this is cool, but it might make sense to create a dropdown component and use it both on header and here. This component was created only for the header, I'm seeing future bugs cause people changing header will change this component 🤔

2017-12-26 15:16 UTC, asantos00 requested changes
See my comment :)

2017-12-26 15:17 UTC, asantos00 requested changes

2017-12-26 15:17 UTC, asantos00 commented on addon/templates/components/uni-header-dropdown-item-simple.hbs
> +  <div class="uni-header__nav__dropdown__list__item--description">{{option.description}}</div>
Be careful, you should check if we're sending description before adding this div, pretty sure this will break something

2017-12-26 15:42 UTC, DaniFrancisco requested changes
just what @asantos00 said

2017-12-27 09:24 UTC, DaniFrancisco approved these changes

2017-12-27 10:32 UTC, asantos00 requested changes
⚠️ Please don't create components manually (we shouldn't do this in ember). This is for a lot of reasons, but in this case, if you had created this component using `ember generate component uni-button-dropdown-item` it would have created some tests :)

Please test this ;) 

Good job 👍

2017-12-27 10:32 UTC, asantos00 commented on addon/styles/partials/_uni-button-dropdown.scss
> +      top: -8px;
Maybe it wasn't you, but this file indentation is all fucked up, CSS should be indented with 4 spaces

2017-12-27 14:21 UTC, asantos00 approved these changes

2017-12-27 14:48 UTC, merged