[NI] Fix template for uni-alert
uniplaces/ember-cli-uniq pull request #223
Opened 2018-01-19 15:13 UTC by niceoutput

2018-01-19 15:17 UTC, mmelo approved these changes

2018-01-19 15:18 UTC, telmaantunes approved these changes

2018-01-21 12:32 UTC, AndreJoaquim requested changes
Do you need the `{{{` in both title and subtitle?

2018-01-22 16:03 UTC, AndreJoaquim approved these changes

2018-01-22 16:04 UTC, merged