[RFC][UN-11734] Add new uni datepicker range
uniplaces/ember-cli-uniq pull request #229
Opened 2018-01-25 01:26 UTC by asantos00

# Issue
https://uniplaces.atlassian.net/browse/UN-10862

# What this does?
This ports part of the calendar done beautifully from @AndreJoaquim in the offer page to ember cli uniq. It is a range calendar and does some of the basic functionality.

Most of the code is his, 🙏 

# Screenshots
TODO

2018-01-25 01:31 UTC, mmelo requested changes
few minor changes, overall great work 👌

2018-01-25 01:31 UTC, mmelo commented on addon/styles/partials/_uni-datepicker-range.scss
> +            @include flex();
change these includes as we no longer use'em

2018-01-25 01:31 UTC, mmelo commented on addon/styles/partials/_uni-datepicker-range.scss
> +        @include align-items-start();
same here mate

2018-01-25 01:31 UTC, mmelo commented on app/components/uni-datepicker-range-day.js
> +export { default } from 'ember-cli-uniq/components/uni-datepicker-range-day';
newline @EOF

2018-01-25 01:31 UTC, mmelo commented on app/components/uni-datepicker-range.js
> +export { default } from 'ember-cli-uniq/components/uni-datepicker-range';
same here sir

2018-01-25 01:31 UTC, mmelo commented on public/assets/images/icons/calendar-arrow.svg
> +
remove empty line please

2018-01-25 01:31 UTC, mmelo commented on public/assets/images/icons/first-highlighted.svg
> +
same here

2018-01-25 01:31 UTC, mmelo commented on public/assets/images/icons/last-highlighted.svg
> +
and here

2018-01-25 01:31 UTC, mmelo commented on public/assets/images/uniplaces_logo.svg
> +<svg viewBox="0 0 2000 480.728"><path fill="#00ADEE" d="M371.259 53.107l-22.384 348.616c-.37 5.838-5.362 9.631-11.095 8.431L224.997 386.43c-16.034-3.369-27.34-12.435-28.787-27.499L168.27 96.34c-.617-
newline @EOF

2018-01-25 01:31 UTC, mmelo commented on public/assets/images/uniplaces_logo_white.svg
> +<svg viewBox="0 0 2000 480.728"><g fill="#FFF"><path d="M371.259 53.107l-22.384 348.616c-.37 5.838-5.362 9.631-11.095 8.431L224.997 386.43c-16.034-3.369-27.34-12.435-28.787-27.499L168.27 96.34c-.617-
same here mate

2018-01-25 10:59 UTC, telmaantunes reviewed
So, I don't know if you are aware but the current calendar in offer page is going through a lot of changes, one of them is the highlighted, that does not work like before. 
Can you please check these layouts and the comments and talk with Fabiano and Cardoso to see if it makes sense to have different calendars? https://app.zeplin.io/project/590c4b4569af7c0dcc4a2575/screen/5a2e8bc0e255a010384a1653?
https://app.zeplin.io/project/590c4b4569af7c0dcc4a2575/screen/5a2e8bceb67ba51760631543?

2018-01-25 15:02 UTC, asantos00 commented
@telmaantunes super pertinent, I knew about that through @mumia. However, this just exports a much simpler calendar to the addon, even though I think the styles should match (the handle and the selected state and blablabla). Ideally, one day (**I dream** 😂) we would be able to have the simpler calendar being used inside the much complex one and they would share styles and so.

At the moment I think it is too much to **loose** more time with this (at least in spa-search), however, I will talk to Fabiano to understand about the next iterations of this calendar (that will almost for sure match the offer page one)

2018-02-06 14:52 UTC, AndreJoaquim approved these changes

2018-03-01 14:29 UTC, mmelo approved these changes

2018-03-01 14:35 UTC, mumia approved these changes

2018-03-01 14:49 UTC, merged