[RFC][NI] Support dynamic options uni autocomplete
uniplaces/ember-cli-uniq pull request #233
Opened 2018-03-01 15:01 UTC by asantos00

# Context
We wanted to use uni-autocomplete but with asynchronous data where `options` where always changing.

# What this does?
Makes the component support dynamic options that can change and just show them instead of filtering

2018-03-01 15:41 UTC, mmelo approved these changes

2018-03-09 11:44 UTC, carantunes approved these changes

2018-03-12 15:03 UTC, AndreJoaquim requested changes

2018-03-12 15:03 UTC, AndreJoaquim commented on addon/components/uni-autocomplete.js
> +  disableFiltering: false,
This flag is not needed, as discussed offline

2018-03-20 11:54 UTC, AndreJoaquim approved these changes

2018-03-20 14:00 UTC, merged