[WIP][UN-12633] uni-tooltip improvements
uniplaces/ember-cli-uniq pull request #240
Opened 2018-04-09 19:00 UTC by carantunes

Related to: https://uniplaces.atlassian.net/browse/UN-12633

2018-04-10 11:19 UTC, AndreJoaquim requested changes

2018-04-10 11:19 UTC, AndreJoaquim commented on addon/components/uni-tooltip.js
> +  wrapperSelector: window,
This should placed with the above content; new line above

2018-04-10 11:19 UTC, AndreJoaquim commented on addon/components/uni-tooltip.js
> +    ev.stopPropagation();
Are we sure we want this all the time?

2018-04-10 11:19 UTC, AndreJoaquim commented on addon/styles/partials/_uni-tooltip.scss
> +    @include breakpoint("x-medium") {
Is this the same? @mmelo @asantos00

2018-04-10 11:26 UTC, carantunes commented on addon/components/uni-tooltip.js
> +    ev.stopPropagation();
I think it makes cense, if a tooltip is placed above another clickable component, say an offer car, only the tooltip should trigger an event. What the rest of the guys think?

2018-04-10 11:29 UTC, mmelo commented on addon/styles/partials/_uni-tooltip.scss
> +    @include breakpoint("x-medium") {
'x-medium': 1100px,

2018-04-10 11:33 UTC, carantunes commented on addon/styles/partials/_uni-tooltip.scss
> +    @include breakpoint("x-medium") {
1100 is a our limit to mobile. anyone as a problem with this?

2018-04-10 13:10 UTC, mmelo commented on addon/styles/partials/_uni-tooltip.scss
> +    @include breakpoint("x-medium") {
none, just stating that 767px of max-with is not the same as x-medium, but if it produces the expected results, I'm ok with it :)

2018-04-12 13:30 UTC, AndreJoaquim approved these changes

2018-04-12 16:32 UTC, merged