[RFC][UN-10990]Uni-tooltip give expand above and below options
uniplaces/ember-cli-uniq pull request #241
Opened 2018-04-11 16:16 UTC by niceoutput

2018-04-11 16:31 UTC, DaniFrancisco approved these changes

2018-04-11 16:45 UTC, sardyy approved these changes

2018-04-11 17:32 UTC, asantos00 requested changes
👍

2018-04-11 17:32 UTC, asantos00 commented on addon/components/uni-tooltip.js
> +      : this.$().offset().top - $(window).scrollTop() + this.$().height() + MARGIN_TOP;
Please extract this to meaningful variables

2018-04-12 10:13 UTC, asantos00 approved these changes
Good job @niceoutput :)

2018-04-12 13:27 UTC, merged