[RFC][UN-11167] Fix page not becoming scrollable
uniplaces/ember-cli-uniq pull request #247
Opened 2018-05-11 15:57 UTC by sardyy

## Context

- Right now, if we have the ```uni-modal``` visible and change the route, the page doesn't become scrollable when it should. To do that, we'd need to toggle the property ```isOpen``` before redirecting to it. I think this behaviour is not expected and the logic should live inside the ```uni-modal``` component itself.

2018-05-11 16:02 UTC, mmelo approved these changes

2018-05-14 09:53 UTC, AndreJoaquim requested changes

2018-05-14 09:53 UTC, AndreJoaquim commented on addon/components/uni-modal.js
> +    $('body').removeClass(OVERFLOW_HIDDEN_CLASS);
New line before, and I think it would be cool to make the `overflowClass` customizable :)

2018-05-14 14:33 UTC, AndreJoaquim approved these changes

2018-05-14 14:46 UTC, merged