[RFC][UN-13768] Move ember-cli-uniq flag folder one level up
uniplaces/ember-cli-uniq pull request #254
Opened 2018-07-18 17:01 UTC by migueldemoura

https://uniplaces.atlassian.net/browse/UN-13768

2018-07-18 17:05 UTC, rntdrts approved these changes

2018-07-19 10:19 UTC, AndreJoaquim requested changes

2018-07-19 10:19 UTC, AndreJoaquim commented on ember-cli-build.js
> -        'public/assets/images/'
Why promoting this change?

2018-07-19 10:19 UTC, AndreJoaquim commented on addon/templates/components/uni-tooltip.hbs
> +        {{inline-svg "images/icons/information-icon"}}
I'm not completely sure how is this going to behave on our platforms

2018-07-19 13:09 UTC, AndreJoaquim approved these changes

2018-07-19 14:41 UTC, AndreJoaquim approved these changes

2018-07-19 14:41 UTC, merged