[RFC][UN-14455]Fix tooltip mobile scroll
uniplaces/ember-cli-uniq pull request #274
Opened 2018-09-19 10:54 UTC by niceoutput

This PR is intended to solve the issue below
https://uniplaces.atlassian.net/browse/UN-14455

2018-09-19 10:57 UTC, mmelo approved these changes

2018-09-19 10:57 UTC, mmelo commented on addon/components/uni-tooltip.js
> +      capture: true,
this fits into a single line mate 👍

2018-09-19 10:58 UTC, DaniFrancisco commented on addon/mixins/click-outside.js
> +    ['click', 'touchstart'].forEach((e) => document.addEventListener(e, clickHandler));
did you check if there are any other components using this mixin? This might affect other stuff

2018-09-19 11:03 UTC, migueldemoura requested changes

2018-09-19 11:03 UTC, migueldemoura commented on addon/mixins/click-outside.js
> +    ['click', 'touchstart'].forEach((e) => document.addEventListener(e, clickHandler));
We can't do it this way. Afaik, `touchend` is triggered when the user releases the finger after touching the screen, which is how we detect a "click". This mixin (`click-outside.js`) has that purpose.

You can try attaching the tooltip close to a mobile scroll, like this:
https://stackoverflow.com/questions/2863547/javascript-scroll-event-for-iphone-ipad

2018-09-19 15:56 UTC, AndreJoaquim requested changes
I don't understand why do we need a scroll event listener on  *every* device to fix a bug on mobile... This should consider only mobile devices -- use the `media` service and add this only on mobile.

2018-09-19 16:23 UTC, DaniFrancisco commented on addon/components/uni-tooltip.js
> +    ['touchstart', 'scroll'].forEach((e) => document.addEventListener(e, clickHandler, { capture: true, passive: true }));
120 chars

2018-09-19 16:23 UTC, DaniFrancisco requested changes

2018-09-19 16:23 UTC, DaniFrancisco commented on addon/components/uni-tooltip.js
> +    console.log('KKKK');
remove

2018-09-19 16:24 UTC, niceoutput commented
@AndreJoaquim This is for mobile and desktop, not mobile only. The title was updated.

2018-09-20 09:59 UTC, DaniFrancisco approved these changes

2018-09-20 16:30 UTC, AndreJoaquim approved these changes

2018-09-20 17:42 UTC, migueldemoura approved these changes

2018-09-21 09:12 UTC, merged