[RFC][UN-15030]Implement message system inside calendar
uniplaces/ember-cli-uniq pull request #293
Opened 2018-11-23 17:20 UTC by niceoutput

https://uniplaces.atlassian.net/browse/UN-15030

<img width="324" alt="screen shot 2018-11-23 at 14 52 37" src="https://user-images.githubusercontent.com/1120141/48955075-18577700-ef44-11e8-838a-2b5809f2ebae.png">

2018-11-24 19:54 UTC, migueldemoura requested changes
Looking good :+1:

2018-11-24 19:54 UTC, migueldemoura commented on tests/integration/components/uni-datepicker-test.js
> +test('it renders', function(assert) {
Change test name to one that's more specific.

2018-11-24 19:54 UTC, migueldemoura commented on tests/integration/components/uni-datepicker-test.js
> +test('it renders', function(assert) {
Change test name to one that's more specific.

2018-11-24 19:54 UTC, migueldemoura commented on tests/integration/components/uni-datepicker-test.js
> +test('it renders', function(assert) {
Change test name to one that's more specific.

2018-11-24 19:54 UTC, migueldemoura commented on tests/integration/components/uni-datepicker-test.js
>  test('it renders', function(assert) {
Change test name to one that's more specific.

2018-11-24 19:54 UTC, migueldemoura commented on addon/components/uni-datepicker.js
> +    })[0];
Do you want this to return undefined when the array is empty? I'd separate the sort from the arr[0] access too.

2018-11-24 19:54 UTC, migueldemoura commented on addon/components/uni-datepicker.js
> +  selectedMessage: computed('messages', function() {
Can you add a comment on the expected behavior of this computed?

2018-11-24 19:54 UTC, migueldemoura commented on addon/components/uni-datepicker.js
> +      return a.type === 'information' ? 1 : -1;
Move the message types to an enum

2018-11-24 19:54 UTC, migueldemoura commented on tests/integration/components/uni-datepicker-test.js
> +    { type: 'information', label: 'This is a information label' },
Use the enum types here, possibly even moving the messages to consts and reuse them across all tests.
Applies to all tests below.

2018-11-26 09:22 UTC, DaniFrancisco requested changes
nothing to add to @migueldemoura 's comments

2018-11-26 11:36 UTC, DaniFrancisco approved these changes

2018-11-26 12:01 UTC, sardyy approved these changes
Nice job 👍

2018-11-26 14:55 UTC, migueldemoura approved these changes

2018-11-26 14:55 UTC, merged