[RFC][UN-15033] Calendar mobile behavior
uniplaces/ember-cli-uniq pull request #296
Opened 2018-11-27 16:48 UTC by niceoutput

https://uniplaces.atlassian.net/browse/UN-15033

![screen shot 2018-11-27 at 16 18 09](https://user-images.githubusercontent.com/1120141/49097248-4995b700-f264-11e8-9af8-a59bcf20f2eb.png)

2018-11-27 17:01 UTC, henrmota approved these changes

2018-11-27 17:01 UTC, mmelo approved these changes

2018-11-27 17:07 UTC, migueldemoura requested changes
Just minor comments 👍

2018-11-27 17:07 UTC, migueldemoura commented on addon/components/uni-datepicker.js
>  import layout from '../templates/components/uni-datepicker';
Move this down

2018-11-27 17:07 UTC, migueldemoura commented on addon/components/uni-datepicker.js
> +  media: service(),
Move this to the top

2018-11-27 17:07 UTC, migueldemoura commented on addon/templates/components/uni-datepicker.hbs
> +  classNames=(if isFullScreen 'mobile')
```suggestion
  classNames=(if isFullScreen "mobile")
```

2018-11-27 17:07 UTC, migueldemoura commented on addon/templates/components/uni-datepicker.hbs
> +    <div class="close-mobile-modal" {{action "closeModalMobile"}}>
```suggestion
    <div class="close-mobile-modal" {{action "onClose"}}>
```

2018-11-27 17:07 UTC, migueldemoura commented on addon/components/uni-datepicker.js
> +    closeModalMobile() {
```suggestion
    onClose() {
```

2018-11-27 17:24 UTC, DaniFrancisco requested changes
Tests missing

2018-11-27 17:24 UTC, DaniFrancisco commented on addon/templates/components/uni-datepicker.hbs
> +    <div class="close-mobile-modal" {{action "closeModalMobile"}}>
`close-modal` only, it shouldn't be necessarily attached to the mobile usecase

2018-11-27 17:24 UTC, DaniFrancisco commented on addon/templates/components/uni-datepicker.hbs
> +  {{#if media.isMobile}}
`isFullscreen`

2018-11-28 14:10 UTC, DaniFrancisco commented on tests/integration/components/uni-datepicker-test.js
> +
rm

2018-11-28 14:10 UTC, DaniFrancisco approved these changes

2018-11-28 14:32 UTC, migueldemoura requested changes
Just noticed that you're not using the new test syntax, which is mandatory. I'd change it as you'll have to do it when merging the FB anyway.

2018-11-28 14:32 UTC, migueldemoura commented on tests/integration/components/uni-datepicker-input-test.js
> +test('test to see if the date picker modal toggle between clicks', async function(assert) {
```suggestion
test('it toggles date picker component existence when clicking input', async function(assert) {
```

2018-11-28 14:32 UTC, migueldemoura commented on tests/integration/components/uni-datepicker-test.js
> +test('test to see if the modal went fullscreen', function(assert) {
Not sure this test should be for this component.

2018-11-28 15:05 UTC, migueldemoura approved these changes

2018-11-28 15:54 UTC, merged