[RFC][UN-15295] Datepicker range select dates logic
uniplaces/ember-cli-uniq pull request #299
Opened 2018-12-10 17:53 UTC by niceoutput

https://uniplaces.atlassian.net/browse/UN-15295

2018-12-10 17:58 UTC, DaniFrancisco requested changes
missing tests for the `minimumDays` feature

2018-12-10 17:58 UTC, DaniFrancisco commented on addon/components/uni-calendar.js
> +  dateRange: computed(function() {
```suggestion
  dateRange: computed('startDate', 'endDate', function() {
```

2018-12-10 17:58 UTC, DaniFrancisco commented on addon/components/uni-calendar.js
> +    getDateAndOpenDatepicker(date, minimumDays) {
`onStartDateSelected`

2018-12-10 17:58 UTC, DaniFrancisco commented on addon/components/uni-calendar.js
> +      let newDate = date.add('days', minimumDays);
```suggestion
      this.set('startDate', date);
      this.set('endDate',  date.add('days', minimumDays));
```

and remove the rest

2018-12-10 17:58 UTC, DaniFrancisco commented on addon/components/uni-datepicker-input.js
> -  onOutsideClick() {
is it working without this? 🤔

2018-12-11 09:58 UTC, DaniFrancisco approved these changes

2018-12-11 16:58 UTC, DaniFrancisco approved these changes

2018-12-11 17:07 UTC, sardyy approved these changes

2018-12-11 17:07 UTC, sardyy commented on tests/integration/components/uni-calendar-test.js
> +  test('it renders the exact date chooosen plus the minimum days', async function(assert) {
fix typo with ```chooosen``` to ```chosen```

2018-12-11 17:12 UTC, henrmota approved these changes

2018-12-11 17:43 UTC, merged