[RFC][NI] Change uni-input-range bindings
uniplaces/ember-cli-uniq pull request #33
Opened 2016-11-16 12:35 UTC by AndreJoaquim

NI

2016-11-16 19:19 UTC, montoias commented on addon/components/uni-input-range.js
> +  isDecrementDisabled: computed('value', function () {
function() {

2016-11-16 19:23 UTC, montoias commented on addon/components/uni-input-range.js
> +      this.get('onChange')(this.get('value') - this.get('offset'));
use Min here to make sure you don't decrement past the value

2016-11-16 19:23 UTC, montoias requested changes

2016-11-16 19:23 UTC, montoias commented on addon/components/uni-input-range.js
> +      this.get('onChange')(this.get('value') + this.get('offset'));
use Max here to make sure you don't decrement past the value

2016-11-17 12:26 UTC, AndreJoaquim commented
@montoias  É carregar no verde

2016-11-17 12:37 UTC, merged