[RFC][UN-7148] Tabs if the user goes back - ember components
uniplaces/ember-cli-uniq pull request #52
Opened 2016-12-05 12:39 UTC by mmelo

Refers to: https://uniplaces.atlassian.net/browse/UN-7148

Created uni-tabs component

2016-12-05 12:57 UTC, AndreJoaquim requested changes

2016-12-05 12:57 UTC, AndreJoaquim commented on addon/templates/components/uni-tabs.hbs
> +            <a href="{{item.url}}">{{item.label}}</a>
this should be a link-to. this way, when a specific route is active, it automatically triggers the active class.
https://guides.emberjs.com/v2.8.0/templates/links/

2016-12-05 12:57 UTC, AndreJoaquim commented on addon/templates/components/uni-tabs.hbs
> +    {{#each tabs as |item|}}
each tabs as tab seems more correct

2016-12-05 12:57 UTC, AndreJoaquim commented on tests/integration/components/uni-tabs-test.js
> +moduleForComponent('uni-tabs', 'Integration | Component | uni tabs', {
Please make some tests :)

2016-12-05 15:07 UTC, mmelo commented
@raffo0707 @montoias @AndreJoaquim fixes made

2016-12-05 16:02 UTC, AndreJoaquim commented
Very good job! 💯 / 💯

2016-12-05 16:02 UTC, AndreJoaquim approved these changes

2016-12-06 01:22 UTC, montoias approved these changes

2016-12-06 01:22 UTC, merged