[RFC][UN-7211] Create carrousel component
uniplaces/ember-cli-uniq pull request #55
Opened 2016-12-07 15:48 UTC by mmelo

Refers to: https://uniplaces.atlassian.net/browse/UN-7211

Added ember carousel component

2016-12-07 17:51 UTC, AndreJoaquim requested changes

2016-12-07 17:51 UTC, AndreJoaquim commented on addon/components/uni-carrousel.js
> +    if (this.get('page') === 0) {
couldnt this be a computed?
```js
showPrev: Ember.computed.eq('page', 0)
```

same for showNext. Then on the template, just wrap the buttons

2016-12-07 17:51 UTC, AndreJoaquim commented on addon/components/uni-carrousel.js
> +      this._update();
you should be able to remove this bearing in mind the changes above proposed

2016-12-07 17:51 UTC, AndreJoaquim commented on addon/components/uni-carrousel.js
> +        this._update();
and this

2016-12-07 17:51 UTC, AndreJoaquim commented on addon/components/uni-carrousel.js
> +        this._update();
...aaaaaand this :D

2016-12-07 17:51 UTC, AndreJoaquim commented on addon/styles/partials/_uni-carrousel.scss
> +    @include carroussel();
If you could just change the mixin name to ```carrousel``` to keep the consistency, would be nice :)

2016-12-07 17:51 UTC, AndreJoaquim commented on addon/styles/partials/_uni-carrousel.scss
> +            transition: background-color $animation-duration $swiftOut;
Can you change the swiftOut here? To "swift-out"?

2016-12-07 17:51 UTC, AndreJoaquim commented on addon/templates/components/uni-carrousel.hbs
> +    <div class="uni-carrousel__container__wrapper" style="transform: translate3d({{deltaX}}px, 0, 0)">
Really need this inline style...? If so, put the 'px' in the second 0, for the reasons you stated before

2016-12-07 17:51 UTC, AndreJoaquim commented on addon/templates/components/uni-modal.hbs
> +  </div>
Undo change

2016-12-07 17:51 UTC, AndreJoaquim commented on tests/integration/components/uni-carrousel-item-test.js
> +  integration: true
Please do some tests. CircleCI is not working for this but we still need to keep the tests passing :)

2016-12-07 17:51 UTC, AndreJoaquim commented on tests/integration/components/uni-carrousel-test.js
> +moduleForComponent('uni-carrousel', 'Integration | Component | uni carrousel', {
same here

2016-12-07 17:55 UTC, montoias requested changes

2016-12-07 17:55 UTC, montoias commented on addon/components/uni-carrousel.js
> +    this.set('deltaX', this.get('page') * this.get('componentWidth') * -1);
this should be computed based on the page

2016-12-07 17:55 UTC, montoias commented on addon/components/uni-carrousel.js
> +      if (this.get('page') > 0) {
create a hasPrev

2016-12-07 17:55 UTC, montoias commented on addon/components/uni-carrousel.js
> +      if (this.get('page') < this.get('items').length - 1) {
has Next

2016-12-07 17:55 UTC, montoias commented on addon/components/uni-carrousel.js
> +    if (this.get('page') === 0) {
why do you need this?

2016-12-07 17:55 UTC, montoias commented on tests/dummy/app/templates/application.hbs
> +      thumbnail=""
ask xavier for those

2016-12-07 17:55 UTC, montoias commented on tests/dummy/app/templates/application.hbs
> +{{#uni-modal isOpen=true title="Photography tips"}}
and this should come from the self-service

2016-12-07 17:55 UTC, montoias commented on tests/dummy/app/templates/application.hbs
> +{{#uni-modal isOpen=true title="Photography tips"}}
otherwise you won't be able to translate

2016-12-07 17:55 UTC, montoias commented on addon/templates/components/uni-carrousel.hbs
> +    <button class="uni-carrousel__button uni-carrousel__button--prev" {{action "prev"}}>&lt;</button>
does xavier want lt?

2016-12-07 17:55 UTC, montoias commented on addon/templates/components/uni-carrousel.hbs
> +    <button class="uni-carrousel__button uni-carrousel__button--next" {{action "next"}}>&gt;</button>
does xavier want gt?

2016-12-07 17:56 UTC, mmelo commented on addon/templates/components/uni-carrousel.hbs
> +    <div class="uni-carrousel__container__wrapper" style="transform: translate3d({{deltaX}}px, 0, 0)">
👀

2016-12-07 19:19 UTC, mmelo commented on addon/templates/components/uni-carrousel.hbs
> +    <button class="uni-carrousel__button uni-carrousel__button--next" {{action "next"}}>&gt;</button>
nop, but we still don't have the svg's for this

2016-12-07 19:19 UTC, mmelo commented on tests/dummy/app/templates/application.hbs
> +{{#uni-modal isOpen=true title="Photography tips"}}
this is just a demonstration of the component, will not ship like this.

2016-12-07 19:19 UTC, mmelo commented on tests/dummy/app/templates/application.hbs
> +      thumbnail=""
same as above

2016-12-07 19:20 UTC, mmelo commented
@AndreJoaquim @montoias added requested fixes

2016-12-07 19:21 UTC, mmelo commented on addon/styles/partials/_uni-carrousel.scss
> +            transition: background-color $animation-duration $swiftOut;
will come in another version of uniq

2016-12-07 19:22 UTC, mmelo commented on tests/integration/components/uni-carrousel-test.js
> +moduleForComponent('uni-carrousel', 'Integration | Component | uni carrousel', {
fixed

2016-12-08 23:09 UTC, montoias commented on tests/dummy/app/templates/application.hbs
> +{{#uni-modal isOpen=true title="Photography tips"}}
👍 

didn't saw it was in dummy dir

2016-12-08 23:09 UTC, montoias commented on tests/dummy/app/templates/application.hbs
> +      thumbnail=""
👍 didn't saw it was in dummy dir

2016-12-08 23:16 UTC, montoias reviewed
A few more changes. Good job!

2016-12-08 23:16 UTC, montoias commented on addon/components/uni-carrousel.js
> +    prev() {
new line

2016-12-08 23:16 UTC, montoias commented on addon/components/uni-carrousel.js
> +    next() {
new line

2016-12-08 23:16 UTC, montoias commented on addon/templates/components/uni-carrousel.hbs
> +            <svg viewBox="0 0 7 11.6">
why isn't this a svg file?

2016-12-08 23:16 UTC, montoias commented on addon/templates/components/uni-carrousel.hbs
> +        <button class="uni-carrousel__button uni-carrousel__button--next" {{action "next"}}>
same

2016-12-08 23:16 UTC, montoias commented on addon/templates/components/uni-carrousel.hbs
> +            <button class="uni-carrousel__container__markers__item {{if (eq page index) "uni-carrousel__container__markers__item--active"}}" {{action "navTo" index}}></button>
you can do instead {{action (mut page)}}

2016-12-08 23:16 UTC, montoias commented on addon/templates/components/uni-carrousel.hbs
> +            <button class="uni-carrousel__container__markers__item {{if (eq page index) "uni-carrousel__container__markers__item--active"}}" {{action "navTo" index}}></button>
and remove also the action associated with navTo

2016-12-09 10:41 UTC, AndreJoaquim approved these changes

2016-12-12 10:53 UTC, montoias commented on addon/templates/components/uni-carrousel.hbs
> +            <button class="uni-carrousel__container__markers__item {{if (eq page index) "uni-carrousel__container__markers__item--active"}}" {{action "navTo" index}}></button>
👍

2016-12-12 10:54 UTC, mmelo commented
@montoias fixed.

2016-12-12 10:55 UTC, merged