[WIP][UN-7884] Add availability types
uniplaces/ember-cli-uniq pull request #99
Opened 2017-02-07 18:14 UTC by montoias

UN-7884

2017-02-13 18:00 UTC, AndreJoaquim requested changes

2017-02-13 18:00 UTC, AndreJoaquim commented on addon/components/uni-datepicker-input.js
> +  formatedDate: computed('selected', function() {
formated => formatted

2017-02-13 18:00 UTC, AndreJoaquim commented on addon/styles/partials/update-availability/_fixed-placeholder.scss
> +  font-size: 15px !important;
em(15px)

2017-02-13 18:00 UTC, AndreJoaquim commented on addon/styles/partials/update-availability/_fixed.scss
> +      font-size: 20px;
em(20px)

2017-02-13 18:00 UTC, AndreJoaquim commented on addon/styles/partials/update-availability/_fixed.scss
> +          color: color('medium-gray') !important;
Do not use this color because this is deprecated

2017-02-13 18:00 UTC, AndreJoaquim commented on addon/styles/partials/update-availability/_fixed.scss
> +          color: color('medium-gray') !important;
Do not use this color because this is deprecated

2017-02-13 18:00 UTC, AndreJoaquim commented on addon/styles/partials/update-availability/_fixed.scss
> +          color: color('medium-gray') !important;
Do not use this color because this is deprecated

2017-02-13 18:00 UTC, AndreJoaquim commented on addon/styles/partials/update-availability/_fixed.scss
> +    font-size: 12px;
em(12px)

2017-02-13 18:00 UTC, AndreJoaquim commented on addon/styles/partials/update-availability/_fixed.scss
> +    background-color: white;
add this to the color pallete of ember-cli-uniq... 'availability',  'background'

2017-02-13 18:00 UTC, AndreJoaquim commented on addon/styles/partials/update-availability/_standard-unitary.scss
> +    background-color: white;
same here

2017-02-13 18:00 UTC, AndreJoaquim commented on addon/styles/partials/update-availability/_standard.scss
> +        background: white;
same here

2017-02-13 18:00 UTC, AndreJoaquim commented on addon/styles/partials/update-availability/_standard.scss
> +      background: white;
same here

2017-02-13 18:00 UTC, AndreJoaquim commented on addon/templates/components/update-availability/fixed.hbs
> +    <div class="link" {{action "addOption"}}>OK</div>
Pass this OK as a label

2017-02-13 18:00 UTC, AndreJoaquim commented on tests/integration/components/update-availability/standard-unitary-test.js
> +  this.render(hbs`
Bons testes :)

2017-02-13 18:00 UTC, AndreJoaquim commented on tests/integration/components/update-availability/standard-test.js
> +  this.render(hbs`{{update-availability/standard}}`);
Bons testes :)

2017-02-13 18:00 UTC, AndreJoaquim commented on tests/integration/components/update-availability/fixed-test.js
> +
Bons testes :)

2017-02-13 18:00 UTC, AndreJoaquim commented on tests/integration/components/update-availability/fixed-placeholder-test.js
> +  assert.equal(this.$().text().trim(), '');
Bons testes :)

2017-02-13 18:00 UTC, AndreJoaquim commented on tests/integration/components/uni-datepicker-input-test.js
> +
Bons testes :)

2017-02-13 18:00 UTC, AndreJoaquim commented on tests/dummy/app/templates/application.hbs
> +{{update-availability/fixed label="option" availability=model.fixed labelAdd='add'}}
Add code snippets

2017-02-14 17:20 UTC, mmelo requested changes
minor fixes requested

2017-02-14 17:20 UTC, mmelo commented on addon/styles/partials/_uni-datepicker.scss
> +  .disabled {
`.disabled:hover {`

2017-02-14 17:20 UTC, mmelo commented on addon/styles/partials/update-availability/_fixed.scss
> +        font-size: 16px;
`font-size: em(16px);`

2017-02-14 17:20 UTC, mmelo commented on addon/styles/partials/update-availability/_fixed.scss
> +    font-size: 14px;
`font-size: em(14px);`

2017-02-14 17:20 UTC, mmelo commented on addon/styles/partials/update-availability/_fixed.scss
> +    font-size: 15px;
`font-size: em(15px);`

2017-02-14 17:20 UTC, mmelo commented on addon/styles/partials/update-availability/_standard-unitary.scss
> +      font-size: 20px;
`font-size: em(20px);`

2017-02-14 17:20 UTC, mmelo commented on addon/styles/partials/update-availability/_standard.scss
> +    font-size: 14px;
`font-size: em(14px);`

2017-02-14 17:20 UTC, mmelo commented on addon/styles/partials/update-availability/_standard.scss
> +      font-size: 12px;
`font-size: em(12px);`

2017-02-15 16:09 UTC, merged